import Head from "next/head";
import Questions from "@/components/Questions";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white h-screen w-full max-w-md mx-auto">
        <Questions />
      </main>
    </>
  );
}
